name: Convert Recipes

on: push

jobs:
  convert_with_pandoc:
    runs-on: ubuntu-latest
    container:
      image: docker://pandoc/core:latest
      options: --entrypoint=pwsh
    steps:
      - uses: actions/checkout@v2
      - name: convert md to html
        shell: pwsh 
        run: ./build.ps1

      - name: Commit files
        id: commit
        run: |
          git config --local user.email "endowdly@gmail.com"
          git config --local user.name "endowdly"
          git add --all

          if ($null -eq $(git status --porcelain)) {
            "::set-output name=push::false"
          }
          else {
            git commit -m "Update Recipes" -a

            "::set-output name=push::true"
          
          } 
        shell: pwsh

      - name: Push changes
        if: steps.commit.outputs.push == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
