name: Convert Recipes

on: push

jobs:
  convert_with_pandoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 

      - name: Get Files
        id: files
        run: echo "::set-output name=files::$(printf '"%s" ' ./src/*.md)" 
 
      - name: Convert Md to Html
        uses: docker://pandoc/core:2.10
        with: 
          args: -d ./pandoc.yaml ${{ steps.files.outputs.files }}

        # run: ./build.ps1
        # run: | 
        #   Get-ChildItem src/*.md |
        #       ForEach-Object { "./src/$_" } |
        #       Set-Variable files
          
        #   pandoc -d ./pandoc.yaml ($files) 

        # run: pandoc -d ./pandoc.yaml ./src/*.md

      - name: Commit Files
        id: commit
        shell: bash
        run: |
          git config --local user.email "endowdly@gmail.com"
          git config --local user.name "endowdly"
          git add --all

          if [-z "$(git status --porcelain)"]; then 
              echo "::set-output name=push::false"
          else
              echo "::set-output name=push::true" 
              
          fi 

        # run:
          # if ($null -eq $(git status --porcelain)) {
          #     "::set-output name=push::false"
          # }
          # else {
          #     git commit -m "Update Recipes" -a

          #     "::set-output name=push::true" 
          # } 

      - name: Push Changes
        if: steps.commit.outputs.push == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
