name: Convert Recipes

on: push

jobs:
  convert_with_pandoc:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    container:
      image: docker://pandoc/core:latest
      options: --entrypoint=sh
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # - name: Get Files
      

      - name: convert md to html
        # run: ./build.ps1
        run: | 
          Get-ChildItem src/*.md |
              ForEach-Object { "./src/$_" } |
              Set-Variable files
          
          pandoc -d ./pandoc.yaml ($files) 

      - name: Commit files
        id: commit
        run: |
          git config --local user.email "endowdly@gmail.com"
          git config --local user.name "endowdly"
          git add --all

          if ($null -eq $(git status --porcelain)) {
              "::set-output name=push::false"
          }
          else {
              git commit -m "Update Recipes" -a

              "::set-output name=push::true" 
          } 

      - name: Push changes
        if: steps.commit.outputs.push == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
