name: Convert Recipes

on: push

jobs:
  convert_with_pandoc:
    runs-on: ubuntu-20.04
    container:
      image: docker://pandoc/core:2.10
      options: --entrypoint=sh
    steps:
      - uses: actions/checkout@v2
      - name: convert md to html
        shell: pwsh 
        run: |
          Get-ChildItem src/*.md |
              ForEach-Object { "./src/$_" } |
              Set-Variable files
              
          pandoc -d pandoc.yaml ($files)

          #find ./src -iname '*.md' -type f -exec sh -c 'pandoc -d ./pandoc.yaml ${0}' {} \;

      - name: Commit files
        id: commit
        run: |
          git config --local user.email "endowdly@gmail.com"
          git config --local user.name "endowdly"
          git add --all

          if ($null -eq $(git status --porcelain)) {
            "::set-output name=push::false"
          }
          else {
            git commit -m "Update Recipes" -a

            "::set-output name=push::true"
          
          } 
        shell: pwsh

      - name: Push changes
        if: steps.commit.outputs.push == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
