name: Convert Recipes

on: push

jobs:
  convert_with_pandoc:
    runs-on: ubuntu-18.04
    container:
      image: docker://pandoc/core:2.10
      options: --entrypoint=sh
    steps:
      - uses: actions/checkout@v2
      - name: convert md to html
        run: |
          find ./src -iname '*.md' -type f -exec sh -c 'pandoc -d ./pandoc.yaml ${0}' {} \;
